name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
    steps:
      - uses: actions/checkout@v4
      - name: Free Disk Space
        run: |
          rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/share/boost
          df -h
      - name: Build APK
        run: |
          export BUILDOZER_ALLOW_ROOT=1
          echo "y" | buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mini-apk
          path: bin/*.apk
