name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
    steps:
      - uses: actions/checkout@v4
      - name: Accept Android SDK Licenses
        run: |
          mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" >> ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license
      - name: Build with Buildozer
        run: |
          echo "y" | buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mini-apk
          path: bin/*.apk
